### ISSUE TITLE
Write code convention BE

### ISSUE THREAD

**Issue by minhhy2801** [PiedTeam/UniqloCloneTraining-BE-Project#1]
Please help add your code convention of BE side

**Comment by bentran1vn** [comment]
# CONVENTIONS

## CODING RULE

**1. Quy ước đặt tên:**

- sử dụng `CamelCase`.
- Đối với hằng số, sử dụng `UPPER_CASE`với `dấu gạch dưới`.
  Ví dụ: `UNAUTHORIZED: 401`.

**2. Thụt lề và khoảng trắng:**

- Sử dụng `tab`.

**3. Dấu ngoặc kép:**

- Sử dụng dấu ngoặc đơn `(‘ ‘)` cho chuỗi ký tự bằng chữ.

**4. Khai báo biến:**

- Khai báo biến bằng `let hoặc const`.

**5. Modularization:**

- Sử dụng `(ES6 import/ export)`.

## FOLDER DESCRIPTION

**1.dist:**

- Thư mục chứa các `file build`.

**2. src:**

- Thư mục chứa mã nguồn.
  vd: `constants, controller....`

**3.src/constants:**

- Chứa các file chứa các hằng số, chứa những thứ xài chung. Ví dụ như là `message, status, Enum`.

**4.src/middlewares:**

- Chứa các file chứa các hàm xử lý **_middleware_**, như `validate, check`.

**5.token, sanitize:**

- Lọc dữ liệu
  vd: người ta gửi 10 file, mình lọc lấy 2 file cho lên server thôi .
- xử lý các dữ liệu **_input_** trước khi vào **_request_**.

**6.src/controllers:**

- Gọi đến service để xử lý logic nghiệp vụ.
- Trả về response, chứa các controller để xử lý request.

**7.src/services:**

- Chứa các file chứa method gọi đến database để xử lý logic nghiệp vụ.
- Chứa các hàm đã xử lý các thông tin.

**8.src/models:**

- Chứa các định nghĩa của thực thể.

**9.src/routes:**

- Chứa các file chứa các route, các đường dẫn API.

**10.src/database:**

- Chứa các file liên quan database.
  ví dụ như: connect, data.

**11.src/utils:**

- Chứa các file chứa các hàm tiện ích, như mã hóa, gửi email, ...
- Còn lại là những file config cho project như `.eslintrc, .prettierrc`, ...

**12.Repository:**

- Là kho để gọi dữ liệu từ database.

**13.Wrapper folder:**

- Code bằng chữ thường.

**14.File:**

Tên đường dẫn theo cú pháp:
`Tên của chủ thể.tên folder Đường dẫn của các thư mục`

**Comment by LeHoDiep** [comment]
@bentran1vn 

- task này không phải cả team cùng làm sao ?
   > ![Image](https://github.com/PiedTeam/UniqloCloneTraining-BE-Project/assets/49841260/58e8e831-46d3-446c-be28-aa2b411ffc3d)
- hãy có một bảng cây thư mục giống thế này để dể đọc và hình dung hơn
  > ![Image](https://github.com/PiedTeam/UniqloCloneTraining-BE-Project/assets/49841260/5a88babe-c313-42f2-b859-3ea3a9fc2c88)

- khai báo biến let const thì khi nào let khi nào const hay thích gì thì mình chọn đó
- Naming cho folder, file thì sao nhỉ, có cần thêm 's' ở cuối không
- Naming cho class và enum, type, interface, function nữa nhé
- Các prop của file json thì dùng upperCase có được không ?
- hãy định nghĩa cho tất cả res, req của một api, việc này sẽ có ích cho fe sau này
  định nghĩa luôn các kết quả của promise  bằng Awaited nhé
- hãy viết định nghĩa, mô tả, đầu vào của các route trong dự án, để dể bảo trì hơn nhé
- function cũng cần được định nghĩa giá trị trả ra, ai viết, hàm làm cái gì, nhận vào cái gì 
- khi mình dùng toán tử so sánh thì phải dùng  == hay ===, hay cái nào cũng được

**Comment by LeHoDiep** [comment]
@bentran1vn  anh chưa thấy các bạn fix convention lại theo review của anh, thì sao các bạn done rồi, vậy thì có cần review nữa không ?

**Comment by bentran1vn** [comment]
Sorry for my mistake i will do it again before 23:00 10/4

**Comment by bentran1vn** [comment]
Mr.Diep @LeHoDiep  here is my complete Coding Convention !

# Create/ Update Product API

- Route: {host}/products
- Method: POST
- Request Model:

```json
{
    "category_Id": "string",
    "product_name": "Ahaha",
    "product_type": "string",
    "product_price": "string",
    "cover_image": "string",
    "product_quantity": "number",
    "release_day": "Date",
    "total_sold": "number",
    "product_description": "string",
    "material": "string",
    "warning": "string",
    "status": "number",
    "product_images": [],
    "product_details": [
        {
            "color": "ProductColor",
            "image": "string",
            "quantities": [
                {
                    "size": "ProductSize",
                    "quantity": "number",
                    "status": "ProductStatus"
                }
            ],
            "create_at": "Date",
            "create_by": "ObjectId"
        }
    ]
}

```

Lúc Create Field total_sold mặc định là bằng 0

Validation:

- product_name: 200 từ
- product_quantity: ≥ 0
- release_day: Không ngày trong quá khứ
- total_sold: ≥ 0
- quantity: ≥ 0

- Response:
    - Create Success:
    
    ```json
    {
    	"status": 200,
    	"message": "Create Product Successfully"
    }
    ```
    
    - Create Fail
    
    Lỗi 422 Unprocessable Enity
    
    ```json
    "status": 422,
    "message": "Unprocessable Enity",
    "data": {
    	"category_Id": "Can not find this category",
    	...
    }
    ```
    
    - Create Fail
        - Ví dụ lỗi Server: Viết code lỗi
        
        → message: Server Error !
        
    
    - Create Fail
        - Ví dụ lỗi Server: Viết code lỗi
        
        → message: Server Error !
        
        - Bị trùng dưới DB:
        
        → message: Product Exists !
        
    
    Lỗi khác 422
    
    ```json
    "status": 500,
    "message": "..."
    ```
    

# Delete Product API

- Route: {host}/products/product_id
- Method: DELETE

- Response:
    - Delete Success:
    
    ```json
    {
    	"status": 200,
    	"message:" "Delete Product Successfully"
    }
    ```
    
    - Delete Fail
        - Ví dụ lỗi Server: Viết code lỗi
        
        → message: Server Error !
        
        - Không có dữ liệu dưới DB:
        
        → message: Invalid Product !
        
    
    ```json
    "status": 500,
    "message": ...
    ```
    

# Get Product API

- Route: {host}/products/product_id
- Method: GET

- Response:
    - Get Product Success:
    
    ```json
    {
    "status": 200,
    "message": "Delete Product Successfully",
    "data": {
        "category_Id": "string",
        "product_name": "Ahaha",
        "product_type": "string",
        "product_price": "string",
        "cover_image": "string",
        "product_quantity": "number",
        "release_day": "Date",
        "total_sold": "number",
        "product_description": "string",
        "material": "string",
        "warning": "string",
        "status": "number",
        "product_images": [],
        "product_details": [
            {
                "color": "ProductColor",
                "image": "string",
                "quantities": [
                    {
                        "size": "ProductSize",
                        "quantity": "number",
                        "status": "ProductStatus"
                    }
                ],
                "create_at": "Date",
                "create_by": "ObjectId"
            }
        ]
    }
}

    ```
    
    - Get Product Fail
        - Ví dụ lỗi Server: Viết code lỗi
        
        → message: Server Error !
        
        - Không có dữ liệu dưới DB:
        
        → message: Can not find Product !
        
    
    ```json
    "status": 500,
    "message": ...
    ```
    

# Get Products API

- Route: {host}/products
- Method: GET
- Query Param:
    - product_name: string
    - material: string
    - sort_by: quantity
    - order: ‘asc’ | ‘desc’
    - num_page: string
    - size_page: string
    
    → Dynamic Search: concat value
    
- Response:
    - Get Product List Success:
    
    ```json
    {
    "status": 200,
    "message": "Get Product List Successfully",
    "data": {
        "products": [
            {
                "category_Id": "string",
                "product_name": "Ahaha",
                "product_type": "string",
                "product_price": "string",
                "cover_image": "string",
                "product_quantity": "number",
                "release_day": "Date",
                "total_sold": "number",
                "product_description": "string",
                "material": "string",
                "warning": "string",
                "status": "number",
                "product_images": [],
                "product_details": [
                    {
                        "color": "ProductColor",
                        "image": "string",
                        "quantities": [
                            {
                                "size": "ProductSize",
                                "quantity": "number",
                                "status": "ProductStatus"
                            }
                        ],
                        "create_at": "Date",
                        "create_by": "ObjectId"
                    }
                ]
            }
        ],
        "num_page": "number",
        "size_page": "number",
        "total_page": "number"
    }
    ```
    
    - Get Product Fail
        - Ví dụ lỗi Server: Viết code lỗi
        
        → message: Server Error !
        
        - Không có dữ liệu dưới DB:
        
        → message: Can not get Product List!
        
    
    ```json
    "status": 500,
    "message": ...
    ```
