### ISSUE TITLE
Research MUI for Component

### ISSUE THREAD

**Issue by bentran1vn** [PiedTeam/UniqloCloneTraining-BE-Project#25]

**Comment by B34R-e** [comment]
_**Report for "Research MUI for Component" task (end-date 09/04/2024):**_
+ Almost understand how to use pre-built components of MUI.
+ Understand custom properties of MUI's components.
+ Can use MUI's components to create Custom Components for using.
+ Familiar with MUI's doc.

Here are 2 demos:
+ Using **Grid**, **Paper**, **Box**, **Typography**, **Rating** to create TourCard.
![Image](https://github.com/PiedTeam/UniqloCloneTraining-BE-Project/assets/92262602/55f7cf30-bbae-444d-91b7-214aa98ea73b)

+ Using **Autocomplete**, **TextField** to create LiveSearchBar.
![Image](https://github.com/PiedTeam/UniqloCloneTraining-BE-Project/assets/92262602/290f1bf8-7433-43cf-ba86-e3c1073994db)

**Comment by bentran1vn** [comment]
Please Review my ticket @minhhy2801
